# SwiftLint configuration for DistributedChat

# Paths to include during linting
included:
  - DistributedChat
  - DistributedChatTests

# Paths to exclude
excluded:
  - DistributedChat.xcodeproj
  - DistributedChatUITests

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - todo
  - missing_docs

# Rule configurations
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

function_parameter_count:
  warning: 8
  error: 10

large_tuple:
  warning: 4
  error: 6

type_name:
  min_length: 3
  max_length: 50

# Custom rules
custom_rules:
  no_print_statements:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use log() function instead of print()"
    severity: warning
